### ISSUE TITLE
How to set SSL certs for Web side

### ISSUE THREAD

**Issue by egdalar** [botlabs-gg/yagpdb#1140]
How am i able to set the SSL certs for the webpage as continually getting.

ERRO http: TLS handshake error from 82.69.41.67:50298: acme/autocert: host "(Censored)" not configured in HostWhitelist  stck="http.(*Server).logf:server.go:3159"

**Comment by ashishjh-bst** [comment]
Did you google for the solution before opening this ticket? Creating and SSL certificate can be done for free for a domain ( LetsEncryprt gives free ssl certificates). 

If you don't have a domain, try running the bot on http instead of https. 


Do not open another issue here, try asking questions in the support server instead.
