### ISSUE TITLE
[Feature Request] Reaction Custom Command DM poster 

### ISSUE THREAD

**Issue by sgoodrow** [botlabs-gg/yagpdb#1152]
Hi everyone,

I would like to suggest an addition to custom commands from reaction triggers.

To facilitate managing request channels, if a user provides an invalid format for their request I would like to be able to react to their post and have the bot send them a DM with some instruments.

The feature request is to allow sending DMs to the poster of the post which has been reacted.

**Comment by LemmeCry** [comment]
From what I understand, you want to DM the message author when you react to the message. This has been discussed in the past and will not be happening because it allows people to possibly spam someone else's DMs via YAGPDB without their consent. This is the reason why `sendDM` does not accept a user argument and only DMs the triggering user.

Additionally, please make suggestions on the [Support server](https://discord.gg/yag) instead of opening issues on the repository.
