### ISSUE TITLE
Try-Catch doesn't seem to work as advertised

### ISSUE THREAD

**Issue by FraganciaGH** [botlabs-gg/yagpdb#1162]
Hello, I decided to give `try-catch` a spin with some intentionally faulty code that is guaranteed to cause an error and execute whatever is inside `catch` but that isn't happening for some reason.

`{{$ObligatoryChannels := dict 0 456 1 789}}
{{range $key, $value := $ObligatoryChannels}}
{{try}}
{{$key.Channel.Type}}
{{$value.Channel.Type}}
{{catch}}
Failed to find a valid channel: {{.Error}}
{{end}}
Worked
{{else}}
Didn't work
{{end}}`
![Screenshot_20220403-123936-234](https://user-images.githubusercontent.com/14110425/161653098-64f613ec-f0da-4a5e-94c2-c62d1e3fc642.png)

**Comment by l-zeuch** [comment]
It does work as implemented, executing the `catch` pipeline if a function call returns an error type as second return value that is not `nil`.

Furthermore, exactly that is pointed out in the documentation:
> Multiple template functions have the possibility of returning an error upon failure. [...]

Your code showcases an error due to wrong syntax, not an error raised by a function call.

See https://github.com/botlabs-gg/template/pull/7 for the source code and an explanation from the original author.

**Comment by FraganciaGH** [comment]
> It does work as implemented, executing the `catch` pipeline if a function call returns an error type as second return value that is not `nil`.
> 
> Furthermore, exactly that is pointed out in the documentation:
> 
> > Multiple template functions have the possibility of returning an error upon failure. [...]
> 
> Your code showcases an error due to wrong syntax, not an error raised by a function call.
> 
> See [botlabs-gg/template#7](https://github.com/botlabs-gg/template/pull/7) for the source code and an explanation from the original author.

Yeah, I was informed on the discord, now I know, closing issue.
![Screenshot_20220405-022147-581](https://user-images.githubusercontent.com/14110425/161654942-99f99ecb-b155-4a36-98ba-c1f76826d058.png)
